### ISSUE TITLE
Unable to download node v4.0.0

### ISSUE THREAD

**Issue by Ormazz** [hokaccha/nodebrew#43]
Hi,

Firstly, thanks for this awesome tools ! It's really enjoyable to develop with it !

Moreover, I have an issue with the install of the node v4.0.0 version.
I'm using the nodebrew 0.9.0 version.

```
$nodebrew install v4.0.0
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/#{ <-- HERE version}/ at /home/florian/.nodebrew/current/bin//nodebrew line 734.
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/#{ <-- HERE release}/ at /home/florian/.nodebrew/current/bin//nodebrew line 734.
fetch: http://nodejs.org/dist/v4.0.0/node-v4.0.0.tar.gz
######################################################################## 100,0%
  File "./configure", line 426
    '''
      ^
SyntaxError: Missing parentheses in call to 'print'
```

Thanks !

**Comment by hokaccha** [comment]
Maybe, this issue is caused by your python's version. node.js can't build by python 3.x(require 2.x).

I recommend to use `install-bainary` command. This dose not compile from source code.

```
$ nodebrew install-bainary v4.0.0
```

**Comment by Ormazz** [comment]
Indeed, the issue was caused by the python's version !

Thanks !
