### ISSUE TITLE
Warning: failed to create the file.

### ISSUE THREAD

**Issue by MikeBarnhardt** [hokaccha/nodebrew#48]
I've added the `$PATH` and `$NODEBREW_ROOT` variable to my `~/.zshrc` config and when I use the command `nodebrew install-binary 0.12.x` it fails:

```
fetch: http://nodejs.org/dist/v0.12.7/node-v0.12.7-darwin-x64.tar.gz
Warning: Failed to create the file
Warning: /usr/local/var/nodebrew/src/v0.12.7/node-v0.12.7-darwin-x64.tar.gz:
Warning: No such file or directory

curl: (23) Failed writing body (0 != 3599)
download faild: http://nodejs.org/dist/v0.12.7/node-v0.12.7-darwin-x64.tar.gz
```

If I `echo $PATH` I get `/Users/Mike/.nodebrew/current/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin` and `echo $NODEBREW_ROOT` gets `/usr/local/var/nodebrew`.

Installed with brew: `brew install nodebrew`. `sudo` gives the same results.

**Comment by MikeBarnhardt** [comment]
After manually creating the directory: `mkdir ~/.nodebrew/src` the commands work fine.

(Also changed `$NODEBREW_ROOT=$HOME/.nodebrew`, but that didn't solve the issue.)

**Comment by hokaccha** [comment]
:+1:

**Comment by flash548** [comment]
still had to do this for the latest nodebrew on macOS (installed using homebrew), then `nodebrew install` commands work
