### ISSUE TITLE
Binary installation should be default?

### ISSUE THREAD

**Issue by 1000ch** [hokaccha/nodebrew#55]
Just **IMHO**.

I guess people use `install-binary` more frequently than `install`.
So binary installation should be easier, isn't it? (Anyway I often use installation from source.)

Such as...

``` ShellSession
$ nodebrew install v4.4.1 # to download compiled binary
$ nodebrew install --source v4.4.1 # to compile from source code
```

Yes, I know this will be breaking change...but nodebrew is still early version `v0.x`.

**Comment by ksato9700** [comment]
:+1:

**Comment by matthewadams** [comment]
👍

**Comment by chuanxd** [comment]
It is a good suggestion.

**Comment by sholladay** [comment]
In the meantime, you can do something like this in your bash startup files.

```sh
alias nbrew='nodebrew install-binary'
```

Then install with:

```console
$ nbrew stable
```

**Comment by gfx** [comment]
+1

@hokaccha what do you think of it?

**Comment by 1000ch** [comment]
🚢
