### ISSUE TITLE
`node brew install-binary stable` installs a wrong version

### ISSUE THREAD

**Issue by Udomomo** [hokaccha/nodebrew#65]
I used this command today, but the installed version is 9.2.0, not 8.9.1.

```
❯ nodebrew install-binary stable
Fetching: https://nodejs.org/dist/v9.2.0/node-v9.2.0-darwin-x64.tar.gz
######################################################################## 100.0%
Installed successfully
```

It doesn't cause any trouble, but I'm wondered why.
I don't know this happens to others too, but please check it.

My environment:
Nodebrew: v0.9.7
node.js: 6.11.4
npm: 3.10.0

**Comment by hokaccha** [comment]
Thank you for your reporting. I fixed the behavior. Please try following commands.

```
$ nodebrew selfupdate
$ nodebrew install-binary stable
```
