### ISSUE TITLE
Support M1 Mac

### ISSUE THREAD

**Issue by eagletmt** [hokaccha/nodebrew#77]
`nodebrew install <version>` on M1 Mac fails with `Error: Darwin arm64 is not supported`
https://github.com/hokaccha/nodebrew/blob/93411b76355860711331de47f669f38f104b7c19/nodebrew#L743

**Comment by vvakame** [comment]
https://github.com/nodejs/node/issues/37309

**Comment by hokaccha** [comment]
Fixed with https://github.com/hokaccha/nodebrew/commit/c58de58dc17384418d7ef9228ddec567eb299678

Note that the M1 Mac binary is only available in v16 and above, so it cannot be installed in v15 and below.
