### ISSUE TITLE
install node.js  old version  is not find  

### ISSUE THREAD

**Issue by YFAnt** [hokaccha/nodebrew#82]
![image](https://user-images.githubusercontent.com/46584057/160733183-927d5602-f75d-46e0-b2ea-33961c2d1c94.png)

**Comment by chuanxd** [comment]
I try version `v14.10.0` successed.

<img width="1669" alt="image" src="https://user-images.githubusercontent.com/4191668/192713086-5ab4a0ca-ff0f-4dd1-8213-cc3c2623f998.png">
